### ISSUE TITLE
Fresh Centos install fail to start

### ISSUE THREAD

**Issue by imtrobin** [Countly/countly-server#917]
Hi, I'm running a fresh install on Centos 7.6, SELinux disabled

wget -qO- http://c.ly/install | sudo bash

No error when installing. The lasts few lines of log didn't show error

Transaction test succeeded
Running transaction
  Installing : python-meld3-0.6.10-1.el7.x86_64                             1/1
  Verifying  : python-meld3-0.6.10-1.el7.x86_64                             1/1

Installed:
  python-meld3.x86_64 0:0.6.10-1.el7

Complete!
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting supervisor
  Downloading https://files.pythonhosted.org/packages/3f/1c/78026a80b8ff35e7c14adb331efb28e6ff2964dbae7e8bd9c52ef7c377a0/supervisor-4.0.3-py2.py3-none-any.whl (296kB)
Collecting meld3>=1.0.0 (from supervisor)
  Downloading https://files.pythonhosted.org/packages/b6/ae/e6d731e4b9661642c1b20591d8054855bb5b8281cbfa18f561c2edd783f7/meld3-1.0.2-py2.py3-none-any.whl
Installing collected packages: meld3, supervisor
  Found existing installation: meld3 0.6.10
ERROR: Cannot uninstall 'meld3'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Webbrowser shows 404
countly status  - Command not found
mongo -  Command not found

**Comment by ar2rsawseen** [comment]
Hello 😃 
this has been fixed by this commit:
https://github.com/Countly/countly-server/commit/7251da92264394368c17817dc5151aa166f41a25

**Comment by imtrobin** [comment]
Hi, actually my problem is not about the meld3, its about unable to start after the installation.

**Comment by ar2rsawseen** [comment]
From your error log it cannot install supervisor because of meld3 and thus cant run process
So fixing that should fix it too

**Comment by imtrobin** [comment]
I see, thanks. Is the script updated or do I have to do manual? Cos I did tried a fresh install two hours ago, and the script is still showing same error

**Comment by ar2rsawseen** [comment]
You can copy the script from latest master here:
https://github.com/Countly/countly-server/blob/master/bin/countly.install_rhel.sh

**Comment by imtrobin** [comment]
Got it working, thanks.
